"""Add missing style fields to Resume

Revision ID: 4d4ab40a2477
Revises: 7055f1698073
Create Date: 2025-08-29 18:11:15.356518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4ab40a2477'
down_revision = '7055f1698073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('font_family', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('font_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('line_spacing', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('line_spacing')
        batch_op.drop_column('font_size')
        batch_op.drop_column('font_family')

    # ### end Alembic commands ###
