"""Add template fields to Resume model

Revision ID: 7055f1698073
Revises: faf0157d7090
Create Date: 2025-08-29 17:33:20.251160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7055f1698073'
down_revision = 'faf0157d7090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('background_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('template_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('template_name')
        batch_op.drop_column('is_template')
        batch_op.drop_column('background_style')
        batch_op.drop_column('theme_color')

    # ### end Alembic commands ###
