"""Add layout column to Resume model

Revision ID: 77d0f021f172
Revises: d5d2eda1e0fe
Create Date: 2025-09-03 16:03:16.222403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d0f021f172'
down_revision = 'd5d2eda1e0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('layout')

    # ### end Alembic commands ###
