"""Allow candidate_id in Resume to be nullable for templates

Revision ID: 88fd6e178fd2
Revises: 4d4ab40a2477
Create Date: 2025-08-29 18:24:29.478052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88fd6e178fd2'
down_revision = '4d4ab40a2477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
