"""Add order column to Experience and Education

Revision ID: d5d2eda1e0fe
Revises: 88fd6e178fd2
Create Date: 2025-08-30 00:09:22.681438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d2eda1e0fe'
down_revision = '88fd6e178fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_column('order')

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
